spring.application.name=ParameterTest

# Web page Setting : 시작주소를 /로 설정
server.servlet.context-path=/  

#server 의 port 변경
server.port = 8080

spring.mvc.view.prefix=/WEB-INF/views/
spring.mvc.view.suffix=.jsp

